# 게시물을 3개 이상 등록한 사람의 정보..
# 두 테이블은 WRITER_ID, USER_ID

# 전체주소는 시, 도로명, 상세주소
# REGEXP_REPLACE('01012345678', '(02|.{3})(.+)(.{4})', '\\1-\\2-\\3');
# => USER_ID, NICKNAME, 전체주소, 전화번호 (형식)

# 회원 아이디 기준 DESC

SELECT j.USER_ID, j.NICKNAME, 
CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, 
CONCAT_WS("-", SUBSTRING(j.TLNO, 1, 3), SUBSTR(j.TLNO, 4, 4), RIGHT(j.TLNO, 4)) AS 전화번호
FROM USED_GOODS_BOARD i 
JOIN USED_GOODS_USER j ON i.WRITER_ID = j.USER_ID
GROUP BY i.WRITER_ID
HAVING COUNT(*) > 2
ORDER BY i.WRITER_ID DESC;