# 거래상태가 DONE이고, 그러한 물건들의 PRICE가 70만원 이상인 사람의
# 회원아이디와 닉네임, 총거래금액.

SELECT j.USER_ID, j.NICKNAME, SUM(i.PRICE) AS TOTAL_SALES
FROM (
    SELECT *
    FROM USED_GOODS_BOARD 
    WHERE STATUS LIKE 'DONE'
) i
JOIN USED_GOODS_USER j
ON i.WRITER_ID = j.USER_ID
GROUP BY i.WRITER_ID
HAVING TOTAL_SALES >= 700000 
ORDER BY TOTAL_SALES;