# 또 요약한번 해보자 우하하
# 22/10/16에 대여중인 거면.... 대여종료일이 저거보다 더 늦거나 같으면! 그러면 대여중, 아니면 대여가능
# 얘와 아이디를 출력하시오.
# 아이디 기준 DESC ~

SELECT DISTINCT CAR_ID, 
    CASE WHEN CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE('2022-10-16') BETWEEN START_DATE AND END_DATE
    ) 
    THEN '대여중'
    ELSE '대여가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC;

SELECT DISTINCT CAR_ID,
    CASE 
        WHEN CAR_ID IN (
            SELECT CAR_ID 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
            WHERE DATE('2022-10-16') BETWEEN START_DATE AND END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END `AVAILABILITY`
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY 1 DESC;