SELECT h.HISTORY_ID, h.CAR_ID, 
DATE_FORMAT(h.START_DATE, '%Y-%m-%d') AS START_DATE, 
DATE_FORMAT(h.END_DATE, '%Y-%m-%d') AS END_DATE,
CASE WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 29 THEN "장기 대여"
ELSE "단기 대여" END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE h.START_DATE LIKE '2022-09%'
ORDER BY h.HISTORY_ID DESC;