SELECT i.BOOK_ID, j.AUTHOR_NAME, 
DATE_FORMAT(i.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK i INNER JOIN AUTHOR j
ON i.AUTHOR_ID = j.AUTHOR_ID
WHERE i.CATEGORY LIKE '경제' 
ORDER BY i.PUBLISHED_DATE;